export const technologies = [
  ["AI", "https://en.wikipedia.org/wiki/Artificial_intelligence"],
  ["AWS", "https://aws.amazon.com/"],
  ["bun", "https://bun.sh/"],
  ["Convex", "https://convex.dev/"],
  ["Docker", "https://www.docker.com/"],
  ["Drizzle", "https://orm.drizzle.team/"],
  ["Expo", "https://expo.dev/"],
  ["GitHub Actions", "https://github.com/features/actions"],
  ["Heroku", "https://www.heroku.com/"],
  ["LLM", "https://en.wikipedia.org/wiki/Large_language_model"],
  ["MongoDB", "https://www.mongodb.com/"],
  ["Neon", "https://neon.tech/"],
  ["Next.js", "https://nextjs.org/"],
  ["OpenAI", "https://openai.com/"],
  ["Playwright", "https://playwright.dev/"],
  ["pnpm", "https://pnpm.io/"],
  ["Postgres", "https://www.postgresql.org/"],
  [
    "React Server Actions",
    "https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions",
  ],
  ["React", "https://react.dev/"],
  [
    "RSC",
    "https://nextjs.org/docs/app/building-your-application/optimizing/rsc",
  ],
  ["Tailwind CSS", "https://tailwindcss.com/"],
  ["tRPC", "https://trpc.io/"],
  ["tubo repo", "https://turbo.build/repo"],
  ["TypeScript", "https://www.typescriptlang.org/"],
  ["Vercel", "https://vercel.com/"],
  ["Vitest", "https://vitest.dev/"],
] as const;
