export const technologies = [
  ["AI", "https://en.wikipedia.org/wiki/Artificial_intelligence"],
  ["AWS", "https://aws.amazon.com/"],
  ["Bun", "https://bun.sh/"],
  ["Convex", "https://convex.dev/"],
  ["CRDTs", "https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type"],
  ["Docker", "https://www.docker.com/"],
  ["DrizzleORM", "https://orm.drizzle.team/"],
  ["ElectricSQL", "https://electric-sql.com/"],
  ["ESLint", "https://eslint.org/"],
  ["Expo", "https://expo.dev/"],
  ["GitHub Actions", "https://github.com/features/actions"],
  ["GraphQL", "https://graphql.org/"],
  ["Heroku", "https://www.heroku.com/"],
  ["LLMs", "https://en.wikipedia.org/wiki/Large_language_model"],
  ["Local-first", "https://localfirstweb.dev/"],
  ["Message queues", "https://en.wikipedia.org/wiki/Message_queue"],
  ["MongoDB", "https://www.mongodb.com/"],
  ["Neon", "https://neon.tech/"],
  ["Next.js", "https://nextjs.org/"],
  ["OpenAI", "https://openai.com/"],
  ["PGlite", "https://pglite.dev/"],
  ["Playwright", "https://playwright.dev/"],
  ["pnpm", "https://pnpm.io/"],
  ["PostgreSQL", "https://www.postgresql.org/"],
  ["Prettier", "https://prettier.io/"],
  ["RabbitMQ", "https://www.rabbitmq.com/"],
  [
    "Server Actions",
    "https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions",
  ],
  ["React", "https://react.dev/"],
  ["REST", "https://en.wikipedia.org/wiki/Representational_state_transfer"],
  [
    "RSC",
    "https://nextjs.org/docs/app/building-your-application/rendering/server-components",
  ],
  ["Solid.js", "https://www.solidjs.com/"],
  ["SolidStart", "https://start.solidjs.com/"],
  ["Storybook", "https://storybook.js.org/"],
  ["Tailwind CSS", "https://tailwindcss.com/"],
  ["tRPC", "https://trpc.io/"],
  ["Turborepo", "https://turbo.build/repo"],
  ["TypeScript", "https://www.typescriptlang.org/"],
  ["Vercel", "https://vercel.com/"],
  ["Vitest", "https://vitest.dev/"],
  ["WebRTC", "https://webrtc.org/"],
  ["WebSockets", "https://en.wikipedia.org/wiki/WebSocket"],
  ["Zod", "https://zod.dev/"],
  ["Cursor", "https://www.cursor.com/"],
  ["Inngest", "https://www.inngest.com/"],
  ["Ably", "https://ably.com/"],
  ["Stripe", "https://stripe.com/"],
  ["Kubernetes", "https://kubernetes.io/"],
  ["Message brokers", "https://en.wikipedia.org/wiki/Message_broker"],
  ["React Native", "https://reactnative.dev/"],
  ["PimDB", "https://www.npmjs.com/package/pimdb"],
  ["Dexie", "https://dexie.org/"],
  [
    "IndexedDB",
    "https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API",
  ],
  ["TS Reset", "https://www.totaltypescript.com/ts-reset"],
  ["tinybench", "https://github.com/tinylibs/tinybench"],
] as const;

type TechnologyName = (typeof technologies)[number][0];

export const highlightedTechnologies: TechnologyName[] = [
  "TypeScript",
  "Next.js",
  "PostgreSQL",
  "MongoDB",
  "Vitest",
  "Playwright",
  "LLMs",
  "OpenAI",
  "ESLint",
];
